Add Docstrings to Exported Functions and Variables
defenseunicorns/zarf pull request #1045
Opened 2022-11-28 15:21 UTC by YrrepNoj

Add (somewhat basic) docstrings to all exportable functions, consts, and package global variables. This is one small step to getting us a cleaner and more standardized codebase.

2022-11-28 15:25 UTC, YrrepNoj commented on src/pkg/packager/common.go
> -	if p.cfg.Pkg.Metadata.Version == "" {
Whoops, this probably shouldn't have been removed.
- [ ] Add it back

2022-11-28 21:47 UTC, Racer159 requested changes

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/message/connect.go
> +		// Loop over each connectStrings and convert to pterm.TableData
dropping each here would make this grammatically correct

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/message/generic.go
> +// Generic represents an implementation of the io.Writer interface
godot

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/message/generic.go
> +// Write writes a byte array to stdout and returns the number of bytes written
godot

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/utils/network.go
> +// IsUrl returns a boolean indicating if the provided string is a valid URL.
IsURL

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/utils/preflight.go
> +// ValidHostname returns a boolean indicating if the provided string is a valid hostname
Hostname or HostName (see below)

2022-11-28 21:47 UTC, Racer159 commented on src/pkg/utils/preflight.go
> +// ValidHostname returns a boolean indicating if the provided string is a valid hostname
also godot

2022-11-29 20:01 UTC, jeff-mccoy commented
Boo I thought you had already merged this in 😭

2022-12-03 00:44 UTC, Racer159 commented
Those conflicting files are gross

2022-12-03 00:51 UTC, jeff-mccoy commented
yeah this something the intern said they were going to merge into the other PR, but it never made it in......

2022-12-05 15:23 UTC, jeff-mccoy commented
So ummm, maybe we close this for now until we have time to look at it again @YrrepNoj ?

2022-12-05 15:29 UTC, closed without merging