Moved duplicate adr 0009
defenseunicorns/zarf pull request #1223
Opened 2023-01-20 13:12 UTC by runyontr

Signed-off-by: Tom Runyon <tom@defenseunicorns.com>

## Description

Duplicate ADR 9s.  This moves the older 9 to 10 to keep ordering

## Related Issue

Fixes #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-01-20 23:01 UTC, jeff-mccoy approved these changes

2023-01-20 23:02 UTC, jeff-mccoy requested changes
Looks like you'll have to sign your commits and then force-push for this one.

2023-01-23 20:35 UTC, Racer159 approved these changes
lgtm

2023-01-24 18:46 UTC, jeff-mccoy commented
Closed, fixed in #1144

2023-01-24 18:46 UTC, closed without merging