Updated push.go
defenseunicorns/zarf pull request #1240
Opened 2023-01-21 19:02 UTC by Yash-C-330

Changed warning message from "Unable to push the git repo" to "retrying" in push.go

## Description

...

## Related Issue

Fixes #1211 

## Type of change

changed the warning message in the push.go

2023-01-27 23:09 UTC, Racer159 requested changes
Requesting changes per the comments in the issue: https://github.com/defenseunicorns/zarf/issues/1211 (the message should include more than the word retrying)

2023-01-30 17:52 UTC, Madeline-UX requested changes
Please review the language that was proposed in the original issue.

2023-02-03 06:25 UTC, YrrepNoj commented
Hey @Yash-C-330 really appreciate you staying on top of keeping this PR update to date :)

I'm going to take another look at the #1211 issue with the team today and come to a conclusion about what we want the exact verbiage to be since there were a couple good ideas discussed but we didn't see to come to a final conclusion yet.

Once we come to a conclusion, we might request you make a few additional change to this PR to match the verbiage we pick. Once again, we very much appreciate you picking up this issue for yourself and keeping the PR up to date 👍

2023-02-03 06:34 UTC, Yash-C-330 commented
Hi, @YrrepNoj thank you for replying, I will be waiting for your request on this issue.

2023-02-14 00:27 UTC, Racer159 requested changes
Thank you for your patience on this, should be gtg after this

2023-02-14 00:27 UTC, Racer159 commented on src/internal/packager/git/push.go
> +		spinner.Warnf("Unable to push the git repo %s because of %w. Retrying the push.", basename, err)
@Yash-C-330 apologies for the delay on this as we work through some other issues in the background, I think the overall flow is correct now but the error unwrapping doesn't print as expected (see below):

![image](https://user-images.githubusercontent.com/3977569/218605955-984351e1-7f22-4457-8a17-19ae625b4698.png)

The following would unwrap this correctly:

```suggestion
		spinner.Warnf("Unable to push the git repo %s (%s). Retrying....", basename, err.Error())
```

2023-02-14 00:27 UTC, Racer159 commented on src/internal/packager/git/push.go
> +		spinner.Warnf("Unable to push the git repo %s because of %w. Retrying the push.", basename, err)
(here is an example of what that above suggestion outputs)
![image](https://user-images.githubusercontent.com/3977569/218606477-66ff3b77-2b41-4efe-8966-3b1af21ee40d.png)

2023-02-14 13:31 UTC, Racer159 approved these changes
lgtm
![image](https://user-images.githubusercontent.com/3977569/218753269-6a4839af-ce47-4982-b672-53484589384c.png)

2023-02-14 15:31 UTC, Madeline-UX approved these changes
Yes, this message thread meets the desired outcomes for keeping the user informed to what is going on at all times.

2023-02-14 15:43 UTC, merged