MZOCI - Make Zarf OCI (Take #2)
defenseunicorns/zarf pull request #1423
Opened 2023-03-08 01:46 UTC by Noxsios

## Description

maybe this time I wont blow up the whole branch... maybe...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-03-08 02:07 UTC, Racer159 requested changes
Ported leftover changes from https://github.com/defenseunicorns/zarf/pull/1402

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	store, err := file.New(p.tmp.Base)
store (isn't  very descriptive.  We should probably pick a name that is consistent between it and dst  (even if it is source and destination)

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	}
Should explain more why we do this artifact then image fallback

2023-03-08 02:07 UTC, Racer159 commented on docs/13-walkthroughs/6-publish-and-deploy.tape
> +Output docs/.images/walkthrough-6.webm
@Noxsios were you going to remove this and the gif?

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/packager/inspect.go
> +				return err
This should be broken into a helper function (or functions) that is able to pull a file from OCI (lines 64-89 are largely repeating)

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	message.Infof("zarf package inspect oci://%s/%s %s", ref.Registry, ref.Repository, flags)
This should be the full ref

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	}
Not a huge fan of these larger inline functions... It can make it harder to follow where the returns are going.

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/utils/bytes.go
> +			wg.Done()
This seems to result in visual glitches on package create 
![image](https://user-images.githubusercontent.com/3977569/223600547-e9aafaff-768b-4e35-937c-10f90a8642bc.png)

2023-03-08 02:07 UTC, Racer159 commented on src/pkg/utils/bytes.go
> +func CheckLocalProgress(progressBar *message.ProgressBar, expectedTotal int64, filepath string, wg *sync.WaitGroup, completeChan chan int, updateText string) {
As mentioned this should probably be moved to avoid the utils import of message.go

2023-03-08 02:07 UTC, Racer159 commented on docs/13-walkthroughs/6-publish-and-deploy.md
> +```
Feedback I took away from watching the user go through the BB walkthrough, can we split this into a Setup section and remove the instructions from the code comments?

```suggestion

## Setup

This walkthrough will require a registry to be configured (see [prerequisites](#prerequisites) for more information).  The below sets up some variables for us to use when logging into the registry:

```bash
$ REGISTRY=docker.io
$ set +o history
$ REGISTRY_USERNAME=<username> # <-- replace with your username
$ REPOSITORY_URL=$REGISTRY/$REGISTRY_USERNAME
$ REGISTRY_SECRET=<secret> # <-- replace with your password or auth token
$ set -o history
```

With those set, you can tell Zarf to login to your registry with the following:

```bash
$ echo $REGISTRY_SECRET | zarf tools registry login $REGISTRY --username $REGISTRY_USERNAME --password-stdin
```
:::note

If you do not have the Docker CLI installed, you may need to create a Docker compliant auth config file manually:

```bash
$ mkdir -p ~/.docker
$ AUTH=$(echo -n "$REGISTRY_USERNAME:$REGISTRY_SECRET" | base64)
# Note: If using Docker Hub, the registry URL is `https://index.docker.io/v1/` for the auth config
$ cat <<EOF > ~/.docker/config.json
{
  "auths": {
    "$REGISTRY": {
      "auth": "$AUTH"
    }
  }
}
EOF
```
:::

```

2023-03-08 02:07 UTC, Racer159 commented on docs/13-walkthroughs/6-publish-and-deploy.md
> +```
Github hates me but hopefully you get the point

2023-03-08 02:07 UTC, Racer159 commented on docs/13-walkthroughs/6-publish-and-deploy.md
> +# Your package tarball may be named differently based on your machine's architecture
This should probably be a :::note

2023-03-08 05:08 UTC, Noxsios commented on src/pkg/packager/publish.go
> +}
Something to talk about during future RCs before this is fully merged.

2023-03-08 05:32 UTC, Noxsios commented
Leaving for myself: https://deploy-preview-1423--zarf-docs.netlify.app/docs/walkthroughs/publish-and-deploy since netlify decided to edit the comment.

2023-03-08 20:36 UTC, Racer159 commented on src/pkg/packager/publish.go
> +}
You mean released?  If so can you create a new issue for tackling it as tech-debt?

2023-03-08 21:09 UTC, Racer159 commented on src/test/e2e/50_oci_package_test.go
> +	require.Contains(t, string(stdOut), "cool-name-podinfo")
Just a note I don't think this is the release name for this example - this should just be the name from normal podinfo - see the oci helm chart fix for a way to test this.

2023-03-10 17:30 UTC, Noxsios commented on src/pkg/packager/publish.go
> +}
will do

2023-03-14 22:25 UTC, Racer159 requested changes
A few changes, one simple, and a few that could be split into future issues.

2023-03-14 22:25 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	dst.ProgressBar.Successf("Published %s [%s]", ref, root.MediaType)
There is an error here with how the progressbar renders (non-blocking but another issue should be created if we decide not to tackle)
![image](https://user-images.githubusercontent.com/3977569/225154301-4452ff56-062f-44d3-97ad-1b4748756390.png)

2023-03-14 22:25 UTC, Racer159 commented on src/pkg/packager/inspect.go
> +		if includeSBOM {
```suggestion
		if includeSBOM || outputSBOM != "" {
```
![image](https://user-images.githubusercontent.com/3977569/225154821-761eead7-2b87-4ed6-abef-bf799c129fe1.png)

2023-03-14 22:25 UTC, Racer159 commented on src/pkg/packager/publish.go
> +}
Can you link the issue here?

2023-03-14 22:25 UTC, Racer159 commented on src/pkg/packager/inspect.go
> +		if includeSBOM {
This *might* be worth having a test for as well...

2023-03-14 23:50 UTC, Noxsios commented on src/pkg/packager/publish.go
> +}
issue here: https://github.com/defenseunicorns/zarf/issues/1434

2023-03-15 00:54 UTC, Racer159 approved these changes
lgtm, passed local tests

2023-03-15 00:55 UTC, merged

2023-03-15 19:46 UTC, bburky commented on src/internal/packager/images/pull.go
> +	// Add an 'org.opencontainers.image.base.name' annotation so we can figure out what the image tag/digest shasum will be during deploy time
The intended purpose of `org.opencontainers.image.base.name` is a base image, like a Dockerfile FROM. This is sort of a misuse of this annotation. The digest here _is_ the same image the base.

I think `org.opencontainers.image.ref.name` is more appropriate? The [image layout specification](https://github.com/opencontainers/image-spec/blob/main/image-layout.md) says it's usually only a tag, but also says there is "no semantic restriction".

2023-03-15 20:29 UTC, bburky commented on src/internal/packager/images/pull.go
> +	// Add an 'org.opencontainers.image.base.name' annotation so we can figure out what the image tag/digest shasum will be during deploy time
@YrrepNoj FYI