Feature: OCI Package Composability
defenseunicorns/zarf pull request #1469
Opened 2023-03-23 07:42 UTC by Noxsios

## Description

...

## Related Issue

Relates to #1426 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-04-07 04:07 UTC, Racer159 requested changes
not a full review, but some things I noticed going through it

2023-04-07 04:07 UTC, Racer159 commented on src/internal/packager/git/pull.go
> +		}
```suggestion
		if strings.HasPrefix(hostPath, "~") {
			// If the path starts with a tilde, we need to expand it to the user's home directory.
			home, err := os.UserHomeDir()
			if err != nil {
				return fmt.Errorf("unable to get user's home directory: %w", err)
			}
			hostPath, err = filepath.Join(home, strings.TrimPrefix(hostPath, "~"))
			if err != nil {
				return fmt.Errorf("unable to convert relative path to absolute path: %w", err)
			}
		} else {
			// The path is relative to the current working directory.
			hostPath, err = filepath.Abs(hostPath)
			if err != nil {
				return fmt.Errorf("unable to convert relative path to absolute path: %w", err)
			}
		}
```

You don't need to reget hostPath, and home is already absolute.

2023-04-07 04:07 UTC, Racer159 commented on src/internal/packager/git/pull.go
> +		// Becomes: file:///home/0x1337/dev/podinfo
This breaks in flux because this isn't where flux transforms these URLs...  This is maybe more obvious with the refactor I did in #809

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (zci ZarfComponentImport) LocalPaths(componentName string) []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (zdi ZarfDataInjection) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (zm ZarfManifest) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (zc ZarfChart) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (zf ZarfFile) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/component.go
> +func (c ZarfComponent) LocalPaths(base string) []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/extensions/bigbang.go
> +func (bb BigBang) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/extensions/common.go
> +type ZarfComponentExtension interface {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/extensions/common.go
> +func (ze ZarfComponentExtensions) LocalPaths() []string {
lint issue

2023-04-07 04:07 UTC, Racer159 commented on src/types/package.go
> +type PathMutation struct {
lint issue

2023-04-12 14:00 UTC, Racer159 requested changes
a few more things

2023-05-05 18:01 UTC, Racer159 requested changes

2023-05-05 18:01 UTC, Racer159 commented on src/types/component.go
> +	URL string `json:"url,omitempty" jsonschema:"description=The URL to a Zarf package,pattern=^(?!.*###ZARF_PKG_TMPL_).*$"`
```suggestion
	URL string `json:"url,omitempty" jsonschema:"description=The URL to a Zarf package to import via OCI,pattern=^(?!.*###ZARF_PKG_TMPL_).*$"`
```

2023-05-05 18:01 UTC, Racer159 commented on src/types/extensions/bigbang.go
> +}
DELETE

2023-05-10 00:02 UTC, Racer159 requested changes

2023-05-10 00:02 UTC, Racer159 commented on src/test/e2e/51_oci_compose_test.go
> +	suite.DirExists(everythingExternal)
Can we add this to .gitignore so that it doesn't get copied if there is a failed/borked test locally.

2023-05-10 01:47 UTC, Noxsios commented on src/pkg/packager/network.go
> +func handleOciPackage(url string, out string, concurrency int, components ...string) error {
that was your suggestion lol

2023-05-10 01:49 UTC, Noxsios commented on src/pkg/packager/network.go
> +	if len(components) > 0 {
With this new behavior, we can rewrite how `inspect` pulls to utilize `handleOCIPackage`, so keeping it named `components` makes more sense.

2023-05-10 20:10 UTC, YrrepNoj requested changes

2023-05-10 20:10 UTC, YrrepNoj commented on src/pkg/packager/publish.go
> +		ref, err = p.ref("")
Nit; can we clean this up a bit?

I would recommend creating a variable for the suffix at the beginning of this function, populate the `skeleton` as needed in the `if` block. and then call `p.ref(refSuffix)` outside of this `else` block.

2023-05-10 20:46 UTC, Noxsios commented on src/pkg/packager/pull.go
> +	p.cfg.DeployOpts.PackagePath = p.tmp.Base
looking at the code, I think this is dead code anyways, removing.

2023-05-11 10:19 UTC, Noxsios commented on src/pkg/packager/compose.go
> +		}
better check implemented

2023-05-12 23:23 UTC, YrrepNoj requested changes

2023-05-12 23:23 UTC, YrrepNoj commented on src/pkg/packager/network.go
> +					estimatedBytes -= node.Size
We should have this logic be computed in the original `getOCIPackageSize()` function

2023-05-12 23:23 UTC, YrrepNoj commented on src/pkg/packager/publish.go
> +			err = archiver.Archive([]string{componentPath + string(os.PathSeparator)}, tarPath)
p.Archive.Component


 @Noxsios i hope you know what that means.

2023-05-12 23:23 UTC, YrrepNoj commented on src/test/e2e/51_oci_compose_test.go
I would suggest building the package and then extracting it out and loading the `zarf.yaml` and performing asserts/requires on the rendered zarf.yaml struct instead of trying to deploy each component.

This would give us the ability to make sure the components were created correctly in finer detail.

2023-05-17 00:56 UTC, Racer159 commented on .gitignore
> +files/
```suggestion
```
can we change coffee ipsum to test-*.txt instead?

2023-05-17 02:24 UTC, Racer159 requested changes

2023-05-17 02:24 UTC, Racer159 commented on src/pkg/packager/create.go
> +					p.cfg.Pkg.Components[index].Manifests[manifestIdx].Kustomizations[kustomizeIdx] = rel
```suggestion
					p.cfg.Pkg.Components[index].Manifests[manifestIdx].Files = append(p.cfg.Pkg.Components[index].Manifests[manifestIdx].Files, rel)
```

2023-05-17 02:24 UTC, Racer159 commented on src/pkg/packager/create.go
> +				p.cfg.Pkg.Components[index].Manifests[manifestIdx].Files = append(p.cfg.Pkg.Components[index].Manifests[manifestIdx].Files, p.cfg.Pkg.Components[index].Manifests[manifestIdx].Kustomizations...)
```suggestion
```

2023-05-17 02:24 UTC, Racer159 commented on src/pkg/packager/publish.go
> +	if strings.HasSuffix(ref.Reference, "-skeleton") {
can this use the const above?

2023-05-17 02:24 UTC, Racer159 commented on src/pkg/packager/pull.go
> +	if strings.HasSuffix(p.cfg.DeployOpts.PackagePath, "-skeleton") {
skeleton

2023-05-17 02:24 UTC, Racer159 commented on src/test/e2e/51_oci_compose_test.go
> +	suite.NoError(err, stdOut, stdErr)
```suggestion
```

2023-05-17 02:24 UTC, Racer159 commented on src/test/e2e/51_oci_compose_test.go
> +	suite.NoError(err, stdOut, stdErr)
```suggestion
```

2023-05-17 02:51 UTC, Racer159 requested changes

2023-05-17 02:51 UTC, Racer159 commented on src/pkg/utils/network.go
> +	OCIURLScheme  = "oci"
lint

2023-05-17 18:15 UTC, YrrepNoj submitted a review, later dismissed

2023-05-17 18:38 UTC, Racer159 approved these changes
lgtm

2023-05-17 18:39 UTC, YrrepNoj approved these changes

2023-05-17 19:58 UTC, merged