Walkthrough edits
defenseunicorns/zarf pull request #1531
Opened 2023-03-31 17:02 UTC by josiblair

## Description
Updates to "Initializing a K8s Cluster" and "Creating a k8s Cluster with Zarf" Walkthroughs
...

## Related Issue

Partial fix for #1377 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-04-03 21:02 UTC, Racer159 requested changes
a few changes.

2023-04-03 21:02 UTC, Racer159 commented on docs/13-walkthroughs/4-creating-a-k8s-cluster-with-zarf.md
> +```
```suggestion
```

### Accessing the Cluster as a Normal User

By default the `k3s` component will only automatically provide cluster access to the `root` user to access the cluster as another user you can run the following to setup the `~/.kube/config` file:

```sh
# cp /root/.kube/config /home/otheruser/.kube
# chown otheruser /home/otheruser/.kube/config
# chgrp otheruser /home/otheruser/.kube/config
```
```

2023-04-03 21:02 UTC, Racer159 commented on docs/13-walkthroughs/4-creating-a-k8s-cluster-with-zarf.md
> +```
Well that borked the suggestion... But that is the rough gist...

2023-04-04 15:51 UTC, YrrepNoj commented on docs/13-walkthroughs/1-initializing-a-k8s-cluster.md
>  zarf destroy --confirm
IMO, I prefer it the way it is, it makes it possible to copy the block and not have to mess around with deleting the first character in the line or having to be careful when highlighting the line to copy.

2023-04-04 23:45 UTC, Racer159 approved these changes
beautiful

2023-04-05 00:15 UTC, merged