adding renovate support for bigbang
defenseunicorns/zarf pull request #1585
Opened 2023-04-11 02:36 UTC by dgershman

## Description

Adding renovate support for Big Bang Releases, inline.  If this is not acceptable will go with the JSON method.

## Related Issue

Relates to #1569 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-04-13 00:06 UTC, Racer159 requested changes
Thanks for the PR! (and apologies it took a bit longer to get to).  I think that this will also need something like the following in the `regexManagers` section of our `renovate.json` as well:

```
  "regexManagers": [
    {
      "fileMatch": [
        "(^|/)zarf.yaml$"
      ],
      "matchStringsStrategy": "recursive",
      "matchStrings": [
        "# renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?( registryUrl=(?<registryUrl>.*?))?\\s.*?version: (?<currentValue>.*)\\s"
      ],
      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"
    }
    ...
  ]
```

At least per: https://docs.renovatebot.com/modules/datasource/gitlab-releases/

You can also test this out here: https://regex101.com/r/w3iKgK/1 (note that renovate requires that you escape backslashes so the `\s`s on regex101 become `\\s` in the renovate.json - you can also compare against the existing regex manager we have for helm charts as well.

2023-04-13 00:14 UTC, dgershman commented
Thanks, you are right!  Updated.

From: Wayne Starr ***@***.***>
Date: Wednesday, April 12, 2023 at 8:06 PM
To: defenseunicorns/zarf ***@***.***>
Cc: Danny Gershman ***@***.***>, Author ***@***.***>
Subject: Re: [defenseunicorns/zarf] adding renovate support for bigbang (PR #1585)

@Racer159 requested changes on this pull request.

Thanks for the PR! (and apologies it took a bit longer to get to). I think that this will also need something like the following in the regexManagers section of our renovate.json as well:

  "regexManagers": [

    {

      "fileMatch": [

        "(^|/)zarf.yaml$"

      ],

      "matchStringsStrategy": "recursive",

      "matchStrings": [

        "# renovate: datasource=(?<datasource>.*?) depName=(?<depName>.*?)( versioning=(?<versioning>.*?))?( registryUrl=(?<registryUrl>.*?))?\\s.*?version: (?<currentValue>.*)\\s"

      ],

      "versioningTemplate": "{{#if versioning}}{{{versioning}}}{{else}}semver{{/if}}"

    }

    ...

  ]

At least per: https://docs.renovatebot.com/modules/datasource/gitlab-releases/

You can also test this out here: https://regex101.com/r/w3iKgK/1 (note that renovate requires that you escape backslashes so the \ss on regex101 become \\s in the renovate.json - you can also compare against the existing regex manager we have for helm charts as well.

—
Reply to this email directly, view it on GitHub<https://github.com/defenseunicorns/zarf/pull/1585#pullrequestreview-1382305475>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAOD3O57JQDGFNOM34GBN7TXA47QRANCNFSM6AAAAAAWZVJAVM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-20 01:52 UTC, Racer159 approved these changes
This lgtm but it looks like your base branch is out of date - not sure if you can enable it but there is a setting to allow changes from maintainers if you'd like - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

2023-04-20 02:22 UTC, dgershman commented
> This lgtm but it looks like your base branch is out of date - not sure if you can enable it but there is a setting to allow changes from maintainers if you'd like - https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

This documentation is pretty bad.  I don't see an obvious way to enable this.

2023-04-20 02:25 UTC, Racer159 commented
> 

Hmm yeah I also think you have to be the "owner" of the repo from my read through it...

2023-04-20 02:25 UTC, Racer159 approved these changes
lgtm

2023-04-20 02:34 UTC, dgershman commented
> > 
> 
> Hmm yeah I also think you have to be the "owner" of the repo from my read through it...

I think this is a bug, it may work for personal repos, but not orgs https://github.com/orgs/community/discussions/5634.

2023-04-20 20:42 UTC, YrrepNoj approved these changes

2023-04-21 13:12 UTC, merged

2023-05-18 02:17 UTC, dgershman commented
It doesn't seem like this is working :(