Zarf walkthrough update
defenseunicorns/zarf pull request #1601
Opened 2023-04-14 15:12 UTC by laurenmengert

## Description

- Updated the 'Using zarf package create' walkthrough
- Changed both the 'Using zarf package create' and 'Deploying zarf packages' walkthroughs to use the helm-oci-chart example
- Abstracted the dos games example from the 'create' and 'deploy' walkthroughs to create a full start to finish walkthrough
- Fixed some grammar
- Standardized some styling 
- Changed order of some pages (I wanted the full dos games walkthrough to come right after the 'deploying zarf packages' one. That seemed to make the most sense to me)
...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-04-19 01:09 UTC, Racer159 commented
> * Regarding the full Dos Games walkthrough - do we think I should add running zarf init? Do we want to make that a true walkthrough of every step, or is just the creation and deployment of the dos-games package enough?
> 
>     * I'd like opinions on whether or not we should keep the video walkthrough that is in the Dos-games section. That video only covers the deployment of the package, whereas the walkthrough article covers the creation _and_ deployment
> 
>     * There was something else but I can't remember.. It will come to me and I'll make another comment or edit this one

I think linking init as a pre-req is fine and we can just focus on create/deploy.

IMO the dos-games video should likely be updated to include both create and deploy and more closely match the walkthrough.

(also there are merge conflicts on this branch that need to be resolved)

2023-04-25 00:03 UTC, Racer159 requested changes
Just a few small suggestions.

2023-04-25 00:03 UTC, Racer159 commented on docs/13-walkthroughs/2-deploying-zarf-packages.md
> +- <https://earthly.dev/blog/dos-gaming-in-docker/>
This isn't needed on the helm one since it is only for the dos walkthrough

2023-04-25 00:04 UTC, Racer159 commented
Also looks like there are a few broken links as well
![image](https://user-images.githubusercontent.com/3977569/234140672-cafa9b33-be19-4040-b4d9-a6084d3c1123.png)

2023-04-25 03:32 UTC, laurenmengert commented on docs/13-walkthroughs/2-deploying-zarf-packages.md
> +If you receive this error when zarf is attempting to deploy the `BASELINE COMPONENT`, this means you have not initialized the kubernetes cluster.  This is one of the prerequisites for this walkthroug
Whoops, good catch

2023-04-25 14:45 UTC, Madeline-UX commented
> > * Regarding the full Dos Games walkthrough - do we think I should add running zarf init? Do we want to make that a true walkthrough of every step, or is just the creation and deployment of the dos-games package enough?
> >   
> >   * I'd like opinions on whether or not we should keep the video walkthrough that is in the Dos-games section. That video only covers the deployment of the package, whereas the walkthrough article covers the creation _and_ deployment
> >   * There was something else but I can't remember.. It will come to me and I'll make another comment or edit this one
> 
> I think linking init as a pre-req is fine and we can just focus on create/deploy.
> 
> IMO the dos-games video should likely be updated to include both create and deploy and more closely match the walkthrough.
> 
> (also there are merge conflicts on this branch that need to be resolved)

I have thought about this some - I think if we were to provide the game as pre-built (on release page) it could all be in one. I struggle with the walkthrough being build and deploy because for a lot of users those tasks will be separate. Although I know package creators will deploy to test. I think the bigger issue is the dos games is an example package. So this should really be how to build a package and how to deploy a package (general steps for packages)

2023-04-28 14:55 UTC, Racer159 commented
> > > * Regarding the full Dos Games walkthrough - do we think I should add running zarf init? Do we want to make that a true walkthrough of every step, or is just the creation and deployment of the dos-games package enough?
> > >   
> > >   * I'd like opinions on whether or not we should keep the video walkthrough that is in the Dos-games section. That video only covers the deployment of the package, whereas the walkthrough article covers the creation _and_ deployment
> > >   * There was something else but I can't remember.. It will come to me and I'll make another comment or edit this one
> > 
> > 
> > I think linking init as a pre-req is fine and we can just focus on create/deploy.
> > IMO the dos-games video should likely be updated to include both create and deploy and more closely match the walkthrough.
> > (also there are merge conflicts on this branch that need to be resolved)
> 
> I have thought about this some - I think if we were to provide the game as pre-built (on release page) it could all be in one. I struggle with the walkthrough being build and deploy because for a lot of users those tasks will be separate. Although I know package creators will deploy to test. I think the bigger issue is the dos games is an example package. So this should really be how to build a package and how to deploy a package (general steps for packages)

I agree though I think I'd like to see https://github.com/defenseunicorns/zarf/issues/758 done first to really build that out - we have the dos games available via sget but this is not likely to be something that most people use as the OCI functionality is much easier for most to use.

2023-04-28 14:58 UTC, Racer159 approved these changes

2023-04-28 15:19 UTC, merged