800. Add sbom section to deploy configure/review
defenseunicorns/zarf pull request #1713
Opened 2023-05-16 17:02 UTC by mike-winberry

## Description
#800 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-05-19 18:02 UTC, mike-winberry commented
https://github.com/defenseunicorns/zarf/assets/86802655/935dd505-7974-4a65-b296-456fa59d02d0

2023-05-19 19:26 UTC, Noxsios commented
A few tweaks:

- Change the triangle "warning" icon on the SBOM section to be amber
- Change the second sentence to be `You can view them here:` and then place the link on a new line

2023-05-21 03:32 UTC, mike-winberry commented
@Racer159 @Madeline-UX 
Made the changes we discussed should be ready to go for full review. 
https://github.com/defenseunicorns/zarf/assets/86802655/8a7a9253-f2f7-47d0-80e8-dac31c4007a5

2023-05-22 15:25 UTC, Madeline-UX submitted a review, later dismissed

2023-05-22 16:23 UTC, Racer159 requested changes

2023-05-22 16:23 UTC, Racer159 commented on src/internal/api/packages/sbom.go
> +	const SBOM = "sboms.tar"
```suggestion
```

`zarf-sbom` is not used and `SBOM` could be placed next to `config.ZarfSBOMDir` as `config.ZarfSBOMTar` replacing the other places the string literal `sboms.tar` is used (`src/pkg/packager/inspect.go`, `src/pkg/packager/common.go`, and `src/cmd/tools/archiver.go`)

2023-05-22 19:46 UTC, Racer159 approved these changes

2023-05-22 21:02 UTC, Noxsios approved these changes
lgtm

2023-05-22 21:02 UTC, merged