Do not check composed filepath
defenseunicorns/zarf pull request #1758
Opened 2023-05-30 19:04 UTC by Noxsios

## Related Issue

Fixes #1756 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-05-30 19:29 UTC, Racer159 requested changes

2023-05-30 19:29 UTC, Racer159 commented on src/pkg/packager/compose.go
> -	// Add prefix for local files.
If the error on create gives back the full path this should be fine

2023-05-31 18:05 UTC, Racer159 commented on src/pkg/packager/compose.go
> -	// Add prefix for local files.
Resolving this as this is how it prints for files that don't exist
![image](https://github.com/defenseunicorns/zarf/assets/3977569/3d85553d-fadd-4f1b-88c7-2ef982a448c2)

2023-05-31 23:09 UTC, Racer159 approved these changes

2023-05-31 23:59 UTC, Noxsios reviewed
lgtm

2023-06-01 00:01 UTC, YrrepNoj approved these changes

2023-06-01 00:13 UTC, merged