Update Big Bang example to include teardown script
defenseunicorns/zarf pull request #1817
Opened 2023-06-13 20:36 UTC by jacobbmay

## Description

The Big Bang example currently tells you to just delete the cluster you deploy to for the cleanup steps. This updates the zarf.yaml to include the teardown steps used by DUBBD so that running zarf package remove successfully uninstalls Big Bang.

[See the zarf.yaml referenced here](https://github.com/defenseunicorns/uds-package-dubbd/blob/main/defense-unicorns-distro/zarf.yaml#L167)

This PR also adds a values file for Neuvector to set the k3s.enabled value to true. Without this value set Neuvector fails to start successfully in k3s cluster because it cannot determine its runtime environment. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-06-13 21:29 UTC, Noxsios commented
@jacobbmay While you are here, would you mind updating the [Big Bang Tutorial `./docs/5-zarf-tutorials/6-big-bang.md`](https://github.com/defenseunicorns/zarf/blob/main/docs/5-zarf-tutorials/6-big-bang.md) to reflect this new info + other DUBBD / BB info?

2023-06-13 21:45 UTC, jacobbmay commented
@Noxsios I actually did include changes to that file to reflect the teardown script but apparently didn't save the file before committing. :facepalm: I will get that committed and pushed.

As far as other information about DUBBD, I don't really know much about it to provide any other info. I only learned of this teardown script after asking about uninstalling Big Bang in slack and one of the DUBBD devs linked me to it.

2023-06-14 19:35 UTC, YrrepNoj submitted a review, later dismissed

2023-06-20 19:26 UTC, Racer159 requested changes

2023-06-21 22:08 UTC, Racer159 approved these changes
lgtm (though we will need to wait for https://github.com/defenseunicorns/zarf/pull/1812 to get in to fixup the tests)

2023-06-22 18:06 UTC, YrrepNoj approved these changes

2023-06-22 21:03 UTC, merged