Draft: Add --no-color option to disable color output
defenseunicorns/zarf pull request #1889
Opened 2023-07-07 15:52 UTC by caesarshift

## Description

Add --no-color option to disable color output
...

## Related Issue

Fixes #890

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-07-07 16:00 UTC, caesarshift commented
I created this as a draft MR in order to get feed back on [this note](https://github.com/defenseunicorns/zarf/issues/890#issuecomment-1625619936)

2023-07-07 17:47 UTC, YrrepNoj commented
Replying to this comment you left on the issue: https://github.com/defenseunicorns/zarf/issues/890#issuecomment-1625619936


The colored log message that says where we're loading the config file from is happening in the [`initViper(...)`](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/viper.go#L83C3-L83C3) function.

That `initViper(...)` is called by the [init function](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/root.go#L79) for `root.go`. Since it's called by an init function, we can not rely on any configuration to be set yet.

If we want to make it so the log message for which config file is being used follows the same configuration as the rest of the logs, we could just move [this line](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/viper.go#L124C13-L124C13) to after we have called `cliSetup(...)`

2023-07-07 19:21 UTC, caesarshift commented
> Replying to this comment @caesarshift left on the issue: [#890 (comment)](https://github.com/defenseunicorns/zarf/issues/890#issuecomment-1625619936)
> 
> The colored log message that says where we're loading the config file from is happening in the [`initViper(...)`](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/viper.go#L83C3-L83C3) function.
> 
> That `initViper(...)` is called by the [init function](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/root.go#L79) for `root.go`. Since it's called by an init function, we can not rely on any configuration to be set yet.
> 
> If we want to make it so the log message for which config file is being used follows the same configuration as the rest of the logs, we could just move [this line](https://github.com/defenseunicorns/zarf/blob/ad5f462135838d11d9ce1080bf4f3b20b35315ad/src/cmd/viper.go#L124C13-L124C13) to after we have called `cliSetup(...)`

Based on your comment, I've added a follow-on [commit](https://github.com/defenseunicorns/zarf/pull/1889/commits/606258566b3034ce0e56e27f377e183af21c8426) that moves the print statements into the cli setup (moving it into the function preserves the order of the output to precede the current log level output)

2023-07-12 18:07 UTC, Noxsios commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
the `--no-color` flag should probably not be passed to `zarf tools` as these sub tools would control their own color (example - `k9s`), so this flag would not do anything + might cause confusion.

2023-07-12 18:33 UTC, caesarshift commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
I agree. However, this would also apply to all the other global flags too, right?

2023-07-15 20:57 UTC, Noxsios commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
Correct, I believe `addHiddenDummyFlag(toolCmd, "no-color")` in `src/cmd/internal.go` is what I am thinking of

2023-07-20 17:38 UTC, Racer159 commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
For the other commands this is controlled via the `isVendorCmd` function - some tools (the one's Zarf itself has) would get the `--no-color` option but the option should not show on vendored commands like `kubectl` or `syft`.

(Notice how this section exists now on the vendored commands:)

```
## Options inherited from parent commands

---
      --no-color   Disable colors in output
---
```

2023-08-02 18:33 UTC, Racer159 commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
@caesarshift just following up on the above to see if there was anything we could help with

2023-08-08 13:27 UTC, caesarshift commented on docs/2-the-zarf-cli/100-cli-commands/zarf_tools.md
Ah, @Noxsios - thanks for clarifying. I  thought you were talking about the cli help documentation that is output when you run the tool, and I couldn't see how I was treating the flag any differently than the other global flags. But this is about the generated docs. Apologies for my confusion. I've made the requested change and regenerated the documentation.

2023-08-08 13:31 UTC, caesarshift commented
FYSA, due to a merge conflict in src/config/config.go, I also rebased the branch.

2023-08-08 21:07 UTC, Racer159 approved these changes
lgtm

2023-08-08 21:16 UTC, cmwylie19 approved these changes
lgtm

2023-08-08 21:39 UTC, Racer159 requested changes

2023-08-09 19:37 UTC, Racer159 commented on src/cmd/viper.go
>  	err := v.ReadInConfig()
Yeah that is likely a fine place for now - there is a big viper refactor in #1898 that will likely make that make a bit more sense (decoupling viper from the root command) but this should be fine for now.

2023-08-10 15:38 UTC, Racer159 approved these changes
lgtm

2023-08-10 15:42 UTC, cmwylie19 approved these changes
lgtm

2023-08-10 15:42 UTC, cmwylie19 approved these changes
lgtm

2023-08-10 17:26 UTC, merged