Refactor paths
defenseunicorns/zarf pull request #1944
Opened 2023-08-02 21:04 UTC by bdfinst

## Description
To prepare the repo for documentation migration and to improve the discoverability of scripts for generating docs, I've renamed `hack/` to `scripts/` and moved the `.templates/` folder with the JSFH configs into `scripts/` path.

This will make doc conversion much cleaner and make it easier to find things.

2023-08-02 23:00 UTC, Racer159 requested changes

2023-08-03 11:42 UTC, bdfinst commented on scripts/create-zarf-schema.sh
> +go run main.go internal config-schema >zarf.schema.json
Must be a  setting in my IDE. I'll check.

2023-08-03 11:53 UTC, bdfinst commented on scripts/syft.tmpl
Done. FYI, `syft.tmpl` is not referenced anywhere.

2023-08-03 12:14 UTC, bdfinst commented on .pre-commit-config.yaml
> -        args: ["--maxkb=1024"]
Due to VS Code setting. Might be a good idea to add a project config file to control that.

2023-08-03 12:27 UTC, bdfinst commented on scripts/.templates/jsfh-config.json
> +}
Bug in VS Code. It's not respecting the .editorconfig setting. I had to explicitly set my IDE to add it. Terrible.

2023-08-04 19:11 UTC, Racer159 requested changes
You will need to run `make docs-and-schema` to update the docs to reference `hack`

2023-08-04 19:11 UTC, Racer159 commented on .pre-commit-config.yaml
this file doesn't need to change

2023-08-04 19:11 UTC, Racer159 commented on CODEOWNERS
The codeowners file should not change

2023-08-04 19:35 UTC, Racer159 approved these changes
lgtm

2023-08-04 21:46 UTC, merged