Implement chart/manifest merging
defenseunicorns/zarf pull request #1975
Opened 2023-08-18 19:01 UTC by Racer159

## Description

This implements more intelligent merging functionality based on the uniqueness of names in `charts` and `manifests`

## Related Issue

Fixes #N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-08-23 17:18 UTC, cmwylie19 requested changes
It doesn't work in practice

2023-08-26 03:03 UTC, Noxsios requested changes
small tweaks, overall logic looked solid

2023-08-26 22:03 UTC, Racer159 commented on src/pkg/utils/yaml.go
> +		ansiRegex := regexp.MustCompile(`\x1b\[(.*?)m`)
Done!

2023-08-26 22:10 UTC, Noxsios approved these changes

2023-08-27 13:07 UTC, cmwylie19 approved these changes
lgtm

2023-08-29 00:13 UTC, merged