1988
defenseunicorns/zarf pull request #1989
Opened 2023-08-25 20:52 UTC by cmwylie19

## Description

Checks if image.Host has already been patched using `helpers.DoHostnamesMatch`

## Related Issue

Fixes #1988

Relates to #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-08-26 21:51 UTC, Racer159 requested changes
looks good but this should probably be unit tested.

2023-08-26 21:51 UTC, Racer159 commented on src/pkg/transform/image.go
> +	if targetHost == image.Host {
This branch of code should have a unit test case added for it

2023-08-27 12:58 UTC, cmwylie19 commented
@Racer159 I took the needs test label off because I think i have covered the newly implemented logic in image_test.go. LMK if you would like to see changes.

2023-08-28 16:33 UTC, Racer159 approved these changes
lgtm

2023-08-28 19:35 UTC, merged