feat: add support for local helm chart tarballs
defenseunicorns/zarf pull request #2066
Opened 2023-10-12 00:38 UTC by Racer159

## Description

This adds support for local charts from tarballs instead of only directories.

## Related Issue

Fixes #2063 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-10-12 00:54 UTC, Noxsios requested changes

2023-10-12 00:54 UTC, Noxsios commented on src/internal/packager/helm/repo.go
please update `src/types/component.go`'s `ZarfChart.LocalPath`'s jsonschema description

2023-10-13 20:27 UTC, Racer159 commented on src/internal/packager/helm/repo.go
done

2023-10-13 22:21 UTC, Noxsios approved these changes
lgtm

2023-10-14 00:17 UTC, Racer159 commented
Moving back to a draft to work more on addressing #1765 - this would require indexing charts like files and data injections.

2023-10-26 19:28 UTC, Racer159 commented
Breaking changes:

1. Chart names must match between `chart.name` and the name in the `Chart.yaml`
2. Charts are now held inside of an indexed folder instead of the root of the component

2023-12-03 02:29 UTC, closed without merging