fix: compose dropping localOS in an only filter
defenseunicorns/zarf pull request #2173
Opened 2023-12-01 22:59 UTC by Racer159

## Description

This fixes an issue where compose could drop the localOS filer through compose.

## Related Issue

Fixes #2158

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [X] Test, docs, adr added or updated as needed
- [X] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-12-05 21:02 UTC, lucasrod16 reviewed
We need to dereference the "composed" pointer on line 47 in `src/pkg/packager/compose.go`:

components = append(components, composed) -> components = append(components, *composed)

2023-12-05 21:03 UTC, lucasrod16 commented on src/pkg/packager/composer/list.go
> +			return composed, err
Would probably be good to update all error handling in `Compose()` to return a nil pointer

```suggestion
			return nil, err
```

2023-12-06 05:16 UTC, Noxsios commented
> We need to dereference the "composed" pointer on line 47 in `src/pkg/packager/compose.go`:
> 
> `components = append(components, composed)` -> `components = append(components, *composed)`

relevant screenshot:

![image](https://github.com/defenseunicorns/zarf/assets/50058333/7dda91df-8fa0-4c60-8cd9-a69e58539ba9)

2023-12-06 19:12 UTC, Noxsios approved these changes

2023-12-06 19:23 UTC, lucasrod16 requested changes

2023-12-06 19:23 UTC, lucasrod16 commented on src/pkg/packager/composer/list.go
Line 228:

`return composed, err` -> `return nil, err`

2023-12-06 19:26 UTC, Racer159 commented on src/pkg/packager/composer/list.go
done

2023-12-06 19:30 UTC, lucasrod16 approved these changes
lgtm

2023-12-06 19:30 UTC, Noxsios approved these changes

2023-12-06 20:37 UTC, merged