feat: add wildcard support to --components
defenseunicorns/zarf pull request #2175
Opened 2023-12-03 04:52 UTC by Racer159

## Description

This adds wildcard and `default` exclusion support to the `--components` field

## Related Issue

Fixes #1794 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [x] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-12-03 04:53 UTC, Racer159 commented
`default` is not implemented yet and the docs need updating

2023-12-03 05:42 UTC, Racer159 commented
`mirror` and `remove` need to be normalized to use the same logic

2023-12-06 03:27 UTC, Racer159 commented
#2035 should be addressed by this issue as well

2023-12-06 19:11 UTC, Noxsios requested changes

2023-12-06 19:11 UTC, Noxsios commented on src/pkg/packager/components.go
> +func confirmOptionalComponent(component types.ZarfComponent) (confirmComponent bool) {
can be moved to `interactive` package if not needed in `packager` anymore

2023-12-06 19:11 UTC, Noxsios commented on src/pkg/packager/components.go
> +func confirmChoiceGroup(componentGroup []types.ZarfComponent) types.ZarfComponent {
can be moved to `interactive` package if not needed in `packager` anymore

2023-12-06 19:11 UTC, Noxsios commented on src/pkg/packager/components.go
> +			included, excluded = includedOrExcluded(component, requestedComponents)
if this function is meant to be used more generically, the `partialMirror` var is a confusing name. Perhaps `isPartial`?

2023-12-06 19:32 UTC, Racer159 commented on docs/3-create-a-zarf-package/2-zarf-components.md
> +If you have any `default` components in a package definition you can also exclude those from the CLI with a trailing `-` (similar to removing a label from a resource with `kubectl`)
I based it on how kubectl removes labels - https://www.golinuxcloud.com/kubectl-label-node/

We could do ! but that is a special character in the shell

2023-12-15 01:15 UTC, Racer159 commented on docs/3-create-a-zarf-package/2-zarf-components.md
> +If you have any `default` components in a package definition you can also exclude those from the CLI with a trailing `-` (similar to removing a label from a resource with `kubectl`)
fine... you won

2023-12-15 01:43 UTC, Racer159 commented on src/internal/packager/helm/post-render.go
> -	defer os.RemoveAll(tempDir)
yes - r.chartPath is inside the temp dir and will be cleaned if Zarf successfully runs - came from this convo: https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1702042791854189

2023-12-15 02:37 UTC, Noxsios commented on docs/3-create-a-zarf-package/2-zarf-components.md
> +If you have any `default` components in a package definition you can also exclude those from the CLI with a trailing `-` (similar to removing a label from a resource with `kubectl`)
at what cost tho

2023-12-15 20:06 UTC, Noxsios requested changes

2023-12-18 21:13 UTC, Noxsios approved these changes

2023-12-18 21:51 UTC, merged