feat: true multi arch OCI
defenseunicorns/zarf pull request #2184
Opened 2023-12-11 00:06 UTC by Noxsios

## Description

...

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2023-12-11 02:39 UTC, Noxsios commented on src/pkg/oci/common.go
> +	if zarfconfig.CommonOptions.Insecure {
true, removed

2023-12-12 06:52 UTC, Noxsios commented on src/pkg/oci/push.go
> +	o.root = nil
`o.root` needs a mutex on it

2023-12-15 18:13 UTC, Noxsios commented
Needs a PR right after the release to update the `examples/composable-packages` skeleton ref to not have `-skeleton`

2023-12-15 21:16 UTC, Racer159 requested changes
partial review

2023-12-16 05:56 UTC, Noxsios commented
Example showing the new tabs that show up in GHCR's UI for multi arch

![Screenshot 2023-12-15 at 11 55 06 PM](https://github.com/defenseunicorns/zarf/assets/50058333/0da6cc51-8b5a-4823-9e6d-7efd258efa0a)

2023-12-18 19:42 UTC, AustinAbro321 commented on src/pkg/packager/publish.go
> +		dstRemote, err := oci.NewOrasRemote(p.cfg.PublishOpts.PackageDestination, oci.WithArch(arch))
Check if there is an old zarf package here and check the architecture rather than using the default on the users machine

2023-12-18 19:42 UTC, AustinAbro321 commented on src/pkg/packager/publish.go
> +		srcRoot, err = srcRemote.ResolveRoot()
Fetching root twice

2023-12-18 19:42 UTC, AustinAbro321 commented on src/pkg/packager/sources/oci.go
> +	isSkeleton := pkg.Build.Architecture == "skeleton" || strings.HasSuffix(s.Repo().Reference.Reference, oci.SkeletonArch)
```suggestion
	// TODO (@Noxsios) remove the suffix check at v1.0.0
	isSkeleton := pkg.Build.Architecture == "skeleton" || strings.HasSuffix(s.Repo().Reference.Reference, oci.SkeletonArch)
```

2023-12-18 19:42 UTC, AustinAbro321 commented on src/test/e2e/50_oci_publish_deploy_test.go
Add a flavor test, just publish and inspect is enough

2023-12-18 21:42 UTC, Racer159 requested changes

2023-12-18 21:42 UTC, Racer159 commented on src/pkg/packager/publish.go
> +			return fmt.Errorf("architecture mismatch (expected: %q, got %q)", arch, pkg.Build.Architecture)
```suggestion
			return fmt.Errorf("architecture mismatch (specified: %q, found %q)", arch, pkg.Build.Architecture)
```

2023-12-18 21:50 UTC, Racer159 approved these changes
lgtm

2023-12-18 22:34 UTC, merged