Included dependency review action
defenseunicorns/zarf pull request #2298
Opened 2024-02-09 17:59 UTC by naveensrinivasan

## Description

- Included dependency review action https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-02-09 19:22 UTC, Racer159 requested changes

2024-02-09 19:22 UTC, Racer159 commented on .github/workflows/dependency-review.yml
> +  dependency-review:
```suggestion
  validate:
```
Changing the job name to validate will make it match our branch protection rules for the repo - we should also consider if/how we might de-conflict this dep review with `.github/workflows/scan-cves.yml` which does similar things (not license checks) but more manually.  We could leave both running to see which output we like better though over time (`grype` has gotten better but had a lot of false positives when we first started).

2024-02-09 22:55 UTC, Racer159 approved these changes
lgtm

2024-02-09 22:55 UTC, Racer159 commented
Code looks good but some commits are not signed - will need to be resigned to merge
![image](https://github.com/defenseunicorns/zarf/assets/3977569/a57a3199-f669-4335-9be7-ab00ba0eab94)

2024-02-12 16:13 UTC, Racer159 requested changes
There is still this unsigned commit in there: 
![image](https://github.com/defenseunicorns/zarf/assets/3977569/e52086c8-8fbd-41fe-9fc3-68b5c0d0fa77)

2024-02-15 18:14 UTC, naveensrinivasan commented
> There is still this unsigned commit in there: ![image](https://private-user-images.githubusercontent.com/3977569/304150736-e52086c8-8fbd-41fe-9fc3-68b5c0d0fa77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMjExNzEsIm5iZiI6MTcwODAyMDg3MSwicGF0aCI6Ii8zOTc3NTY5LzMwNDE1MDczNi1lNTIwODZjOC04ZmJkLTQxZmUtOWZjMy02OGI1YzBkMGZhNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMTgxNDMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVlYmNmODlkZWFlMDNkYWIwM2JlYjZjZjkzMWM2OTVkNzYzNzk2MTEwNTlhYzVmNWNmOWJhYzk0ODc4ODU0NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iiroziXDoW4CsQjLjL2irhYlHqpZpSu0nzDIFTIUniI)

Can you please check now?

2024-02-16 20:11 UTC, Noxsios commented
Approving. Will need to circle back in a few weeks/months to evaluate how much of a value add / noise this generates.

2024-02-16 20:17 UTC, Noxsios requested changes

2024-02-16 20:17 UTC, Noxsios commented on .github/workflows/dependency-review.yml
> +on: [pull_request]
```suggestion
name: Dependency Review
on: pull_request
```

tiny consistency tweak

2024-02-16 20:17 UTC, Noxsios commented on .github/workflows/dependency-review.yml
> +      - name: 'Dependency Review'
```suggestion
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Dependency Review
```

2024-02-16 23:24 UTC, Racer159 approved these changes
lgtm

2024-02-16 23:25 UTC, Noxsios approved these changes

2024-02-20 18:07 UTC, merged