chore: fixes potential cross site scripting
defenseunicorns/zarf pull request #2344
Opened 2024-03-01 15:24 UTC by naveensrinivasan

## Description

- fixes  `G203: The used method does not auto-escape HTML. This can potentially lead to 'Cross-site Scripting' vulnerabilities in case the attacker controls the input. (gosec)`

## Related Issue

Fixes #

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md#developer-workflow) followed

2024-03-01 15:55 UTC, Racer159 requested changes

2024-03-01 15:55 UTC, Racer159 commented on src/internal/packager/sbom/viewer.go
> +		Data:      template.JS(safeJsonData),
```suggestion
		List:      template.JS(safeJSONList),
		Data:      template.JS(safeJSONData),
```
linting

2024-03-01 17:54 UTC, naveensrinivasan commented on src/internal/packager/sbom/viewer.go
> +	safeJsonList := template.JSEscapeString(string(b.jsonList))
Thanks. I took care of this.

2024-03-01 17:54 UTC, naveensrinivasan commented on src/internal/packager/sbom/viewer.go
> +		Data:      template.JS(safeJsonData),
Thanks. I took care of this.

2024-03-04 03:00 UTC, Racer159 requested changes

2024-03-04 03:00 UTC, Racer159 commented on src/internal/packager/sbom/viewer.go
> +		Data:      template.JS(safeJSONData),
Should have checked earlier, but this actually breaks the way we are including these values into the sbom html files:

![image](https://github.com/defenseunicorns/zarf/assets/3977569/186f51fa-6a2d-43d9-8c76-bd858b41a864)

(note the escaped values)

![image](https://github.com/defenseunicorns/zarf/assets/3977569/9a3cdeab-66d4-4665-ae0e-62550b535ab3)

simple repro:

```
zarf package create examples/dos-games/
zarf package inspect zarf-package-dos-games-amd64-1.0.0.tar.zst -s
```

2024-03-04 15:53 UTC, Racer159 commented
After more thought and discussion, closing this since the threat surface is lower (would require modifying syft json data and there aren't any creds to steal on the site given it is a static HTML page).  Fixing this would likely require more effort than it is worth at this juncture.

2024-03-04 15:53 UTC, closed without merging