Add skeleton of new E2E test for testing the Data Injection example
defenseunicorns/zarf pull request #242
Opened 2022-01-24 22:15 UTC by RothAndrew

2022-01-24 22:15 UTC, RothAndrew commented
/test all

2022-01-24 22:16 UTC, RothAndrew commented
@jeff-mccoy this is the setup (not including the test code, which is just commented out from a different test) that currently exists for adding a new E2E test.

2022-01-24 22:17 UTC, RothAndrew commented
99% of it is just copy/pasted from previous tests.

2022-01-24 22:19 UTC, RothAndrew commented
Since GitHub Actions only looks at Master this needs to get merged before the actual test gets written since it adds a new GHA Job

2022-01-24 22:29 UTC, RothAndrew commented
/test all

2022-01-25 17:43 UTC, YrrepNoj commented on .github/workflows/test-command.yml
> +  # Run the E2E test of the Data Injection example
nit: This is a copy of the comment on line 363, it doesn't seem like it's supposed to be.

2022-01-25 17:43 UTC, YrrepNoj requested changes
small comment change then it's good to go

2022-01-26 18:18 UTC, RothAndrew commented
/test all

2022-01-26 18:44 UTC, YrrepNoj submitted a review, later dismissed

2022-01-26 18:50 UTC, RothAndrew commented
/test all

2022-01-26 18:56 UTC, RothAndrew commented
@YrrepNoj one more review please. I had to force push a new commit to fix a GPG signing issue

2022-01-26 18:57 UTC, YrrepNoj approved these changes

2022-01-26 19:05 UTC, merged