test: clean up tests for composer
defenseunicorns/zarf pull request #2532
Opened 2024-05-22 07:26 UTC by phillebaba

## Description

Cleans up the composer tests to the newer testing style.

## Related Issue

Relates to #2512 

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed

2024-05-22 14:54 UTC, AustinAbro321 requested changes

2024-05-22 14:54 UTC, AustinAbro321 commented on src/pkg/packager/composer/list_test.go
> +		expectedErrorMessage string
Nit: get rid of return error and just check if `expectedError != ""`

2024-05-22 14:54 UTC, AustinAbro321 commented on src/pkg/packager/composer/list_test.go
> +		expectedErrorMessage string
and the error isn't used anyway

2024-05-22 18:49 UTC, Noxsios reviewed
no additions outside what @AustinAbro321 commented on

2024-05-23 15:17 UTC, schristoff-du approved these changes

2024-05-23 22:22 UTC, merged