refactor: remove use of k8s secret
defenseunicorns/zarf pull request #2565
Opened 2024-05-31 07:47 UTC by phillebaba

## Description

Removes use of k8s secret functions.

## Related Issue

Relates to #2507

## Checklist before merging

- [ ] Test, docs, adr added or updated as needed
- [ ] [Contributor Guide Steps](https://github.com/defenseunicorns/zarf/blob/main/.github/CONTRIBUTING.md#developer-workflow) followed

2024-06-13 12:01 UTC, AustinAbro321 requested changes
K8s package is almost gone!

2024-06-13 12:11 UTC, phillebaba commented on src/pkg/packager/remove.go
> +			}
This should be replaced with SSA TBH but I want to do it in a separate PR for all resources. That should remove any need for create or update.

2024-06-13 12:27 UTC, AustinAbro321 commented on src/pkg/packager/remove.go
> +			}
By SSA you mean this function call  `c.Clientset.CoreV1().Secrets(cluster.ZarfNamespaceName).Apply` ?

2024-06-13 14:28 UTC, lucasrod16 approved these changes
Left a small nit that doesn't have to be addressed in this PR

2024-06-13 14:28 UTC, lucasrod16 commented on src/pkg/packager/remove.go
> +		newPackageSecretData, _ := json.Marshal(deployedPackage)
Not sure if you meant to leave this here, but I think we should handle this error and remove the TODO comment

2024-06-14 09:48 UTC, phillebaba commented on src/pkg/packager/remove.go
> +			}
Yes

2024-06-14 12:59 UTC, phillebaba commented
I have created #2626 to track @AustinAbro321 comments about the verbosity of create or update.

2024-06-14 13:16 UTC, AustinAbro321 approved these changes

2024-06-14 13:16 UTC, merged