implement component choice groups
defenseunicorns/zarf pull request #488
Opened 2022-05-23 08:12 UTC by jeff-mccoy

Fixes #487 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist before merging

- [ ] Tests have been added/updated as necessary (add the `needs-tests` label)
- [ ] Documentation has been updated as necessary (add the `needs-docs` label)

2022-05-23 08:16 UTC, jeff-mccoy commented
Prompt for choosing which component to deploy:
<img width="1066" alt="Screen Shot 2022-05-22 at 5 09 53 PM" src="https://user-images.githubusercontent.com/882485/169774663-f2f2020a-5092-4406-b31c-3663abf3f3ce.png">

After selection:
<img width="839" alt="Screen Shot 2022-05-22 at 5 10 16 PM" src="https://user-images.githubusercontent.com/882485/169774739-1ba8185c-0d45-4565-8e2f-71157317b47f.png">

Error message if attempting to specify more than one component from a choice group:
<img width="858" alt="Screen Shot 2022-05-23 at 2 59 56 AM" src="https://user-images.githubusercontent.com/882485/169774813-d4b4883e-6d5a-4658-b9fa-1a69f861f7d0.png">

2022-05-23 08:48 UTC, jeff-mccoy commented
Updated zarf init credential examples: 

`zarf init --confirm`
<img width="927" alt="Screen Shot 2022-05-23 at 3 43 28 AM" src="https://user-images.githubusercontent.com/882485/169780692-ecd6f208-003b-4ba2-a115-750b12c09f4a.png">

`zarf init --confirm --components=logging`
<img width="902" alt="Screen Shot 2022-05-23 at 3 46 10 AM" src="https://user-images.githubusercontent.com/882485/169780808-b28b6e4b-d622-46cd-b639-990ce480f080.png">

`zarf init --confirm --components=git-server`
<img width="926" alt="Screen Shot 2022-05-22 at 5 28 40 PM" src="https://user-images.githubusercontent.com/882485/169780915-755244f9-311e-47df-99e7-9e12ff069479.png">

2022-05-23 20:57 UTC, YrrepNoj requested changes

2022-05-23 20:57 UTC, YrrepNoj commented on src/internal/packager/components.go
> +				if component.Name == "k3s" && config.IsZarfInitConfig() {
we have a `k8s.DistroIsK3s` const we can use here to check against instead of using a hardcoded string

2022-05-23 20:57 UTC, YrrepNoj commented on src/internal/packager/components.go
> +		componentGroups[key] = append(componentGroups[key], component)
Reading through this just made me realize that we don't validate component names are unique within a package. Could you add that to this PR too (or write an issue if you don't think it fits in this PR's scope)?

2022-05-24 06:50 UTC, jeff-mccoy commented on packages/big-bang-core/zarf.yaml
> +    description: "Deploy a lightweight demo version of Big Bang Core not intended for production use"
I don't want to have too many opinions around this and would like to leave it up to the community to figure out what makes sense.  That being said, I did change the wording a little bit.

2022-05-24 14:48 UTC, merged